### PR TITLE
Add Battery Guru

### PR DESCRIPTION
**Pull request by Zxis233**
RT

### CODE REVIEW

**Comment by TeaOwO** [comment]
It looks like the app doesn't follow dynamic nor MD3 guidelines.

**Comment by TeaOwO** [comment]
You're using the wrong link, make it this "https://www.apkmirror.com/apk/paget96/battery-guru-health-saver/"

**Comment by Zxis233** [comment]
That's my fault. Sorry!

**Review by TeaOwO — CHANGES_REQUESTED** [review]
You're using the wrong link, change it to this "https://www.apkmirror.com/apk/paget96/battery-guru-health-saver/" + add the app to "newly added apps". Anyways, thank you :3

**Review by TeaOwO — APPROVED** [review]

**Comment by TeaOwO** [comment]
Thanks! :3

**Pull request merged**
