### PR TITLE
Aegis MD3 is released. No need to build.

### PR DESCRIPTION
**Pull request by arshit09**

### CODE REVIEW

**Review by TeaOwO — COMMENTED** [review]
But there isn't a release? Can you send me a link?

**Comment by TeaOwO** [comment]
Will be closing until you reply.

**Comment by arshit09** [comment]
This link https://github.com/Wojtaz0w/Aegis-MD3 has the the released app link of Play Store and F-droid.
So we don't need to build it, right?
Or am I missing something?

**Comment by TeaOwO** [comment]
> This link https://github.com/Wojtaz0w/Aegis-MD3 has the the released app link of Play Store and F-droid. So we don't need to build it, right? Or am I missing something?

For now that just links to regular (MD2) aegis. You still need to build it to get the MD3 version (there is a PR to make the play store and f-droid link to aegis MD3) but for now you have to build it.

**Comment by Wojtaz0w** [comment]
I didn't create Aegis-MD3 for public usage... my repo exists because I made a PR to original Aegis, tho I won't stop anyone from using it 🙂

**Comment by Wojtaz0w** [comment]
Thank you for your kind words 😀❤️

**Comment by fuzzzerd** [comment]
> > I didn't create Aegis-MD3 for public usage... my repo exists because I made a PR to original Aegis, tho I won't stop anyone from using it 🙂
> 
> Yeah I know. I wouldn't usually add a repository like this (aegis-md3) since it's just used to PR to the main repo. However, it seemed fine for public usage. Will replace the link once the PR gets merged.
> 
> Also, you did a great job with making the app follow MD3 standards <3

That's really misleading. There's no indication in this list if the link is to the main repo or a fork. Obviously you can click through and find out for yourself, but that feels disingenuous at best. Especially for an app like Aegis, which is security oriented, the source is important.

**Comment by TeaOwO** [comment]
> > > I didn't create Aegis-MD3 for public usage... my repo exists because I made a PR to original Aegis, tho I won't stop anyone from using it 🙂
> > 
> > 
> > Yeah I know. I wouldn't usually add a repository like this (aegis-md3) since it's just used to PR to the main repo. However, it seemed fine for public usage. Will replace the link once the PR gets merged.
> > Also, you did a great job with making the app follow MD3 standards <3
> 
> That's really misleading. There's no indication in this list if the link is to the main repo or a fork. Obviously you can click through and find out for yourself, but that feels disingenuous at best. Especially for an app like Aegis, which is security oriented, the source is important.

Yes, Im sorry. I'm kinda confused on wether I should delete the app from the list, or simply add the fork tag?

**Comment by Wojtaz0w** [comment]
> > > > I didn't create Aegis-MD3 for public usage... my repo exists because I made a PR to original Aegis, tho I won't stop anyone from using it 🙂
> > > 
> > > 
> > > Yeah I know. I wouldn't usually add a repository like this (aegis-md3) since it's just used to PR to the main repo. However, it seemed fine for public usage. Will replace the link once the PR gets merged.
> > > Also, you did a great job with making the app follow MD3 standards <3
> > 
> > That's really misleading. There's no indication in this list if the link is to the main repo or a fork. Obviously you can click through and find out for yourself, but that feels disingenuous at best. Especially for an app like Aegis, which is security oriented, the source is important.
> 
> Yes, Im sorry. I'm kinda confused on wether I should delete the app from the list, or simply add the fork tag? 

I think it would be best to delete. I don't have malicious intensions, but I created repo solely for the purpose of making a pull request - I'm not going to maintain it, therefore I haven't published any APKs.

**Comment by TeaOwO** [comment]
> > > > > I didn't create Aegis-MD3 for public usage... my repo exists because I made a PR to original Aegis, tho I won't stop anyone from using it 🙂
> > > > 
> > > > 
> > > > Yeah I know. I wouldn't usually add a repository like this (aegis-md3) since it's just used to PR to the main repo. However, it seemed fine for public usage. Will replace the link once the PR gets merged.
> > > > Also, you did a great job with making the app follow MD3 standards <3
> > > 
> > > 
> > > That's really misleading. There's no indication in this list if the link is to the main repo or a fork. Obviously you can click through and find out for yourself, but that feels disingenuous at best. Especially for an app like Aegis, which is security oriented, the source is important.
> > 
> > 
> > Yes, Im sorry. I'm kinda confused on wether I should delete the app from the list, or simply add the fork tag?
> 
> I think it would be best to delete. I don't have malicious intensions, but I created repo solely for the purpose of making a pull request - I'm not going to maintain it, therefore I haven't published any APKs.

I guess this answers it, thanks <3

**Comment by TeaOwO** [comment]
Changes made https://github.com/TeaOwO/Material-You-Apps/commit/88fd232c79c6882f1f5243eb6646d8fad84ab929

**Pull request closed without merging**
